import { useState, useRef } from "react";
import { useUIStore, useMessageStore } from "@/store";
import { toast } from "sonner";
import { db } from "@/db/db";
import { createMessage, deleteExpiredMessages } from "@/db/messages";
import { v4 as uuidv4 } from "uuid";
import type { Message, MessageType } from "@/types/message";

export default function Settings() {
  const { isNavigating, setNavigating } = useUIStore();
  const { fetchMessages } = useMessageStore();
  
  // Stealth Dev Mode State
  const [devModeEnabled, setDevModeEnabled] = useState(false);
  const tapCountRef = useRef(0);
  const tapTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const handleSecretTap = () => {
    if (devModeEnabled) return;

    if (tapTimeoutRef.current) {
      clearTimeout(tapTimeoutRef.current);
    }

    tapCountRef.current += 1;

    if (tapCountRef.current >= 5) {
      setDevModeEnabled(true);
      toast.success("Developer Mode Unlocked");
      tapCountRef.current = 0;
    } else {
      // Reset tap counter if they don't tap again within 500ms
      tapTimeoutRef.current = setTimeout(() => {
        tapCountRef.current = 0;
      }, 500);
    }
  };

  const handleGenerateMessages = async () => {
    try {
      const types: MessageType[] = ["alert", "news", "route", "resource"];
      for (let i = 0; i < 50; i++) {
        const type = types[Math.floor(Math.random() * types.length)];
        const msg: Message = {
          id: `msg_${uuidv4().substring(0, 8)}`,
          type,
          priority: type === "alert" ? "high" : "low",
          content: `Automated test message ${i + 1} generated by Dev Tools.`,
          createdAt: Date.now() - Math.floor(Math.random() * 10000000),
          updatedAt: Date.now(),
          expiresAt: Date.now() + 86400000,
          version: 1,
          hopCount: Math.floor(Math.random() * 5),
          maxHopCount: 10,
          trusted: true
        };
        await createMessage(msg);
      }
      await fetchMessages();
      toast.success("50 dummy messages generated successfully!");
    } catch (error) {
      toast.error("Failed to generate dummy messages.");
    }
  };

  const handleClearDatabase = async () => {
    try {
      await db.messages.clear();
      await fetchMessages();
      toast.warning("Database cleared completely.");
    } catch (error) {
      toast.error("Failed to clear database.");
    }
  };

  const handleTTL = async () => {
    try {
      await deleteExpiredMessages();
      await fetchMessages();
      toast.info("TTL Cleanup triggered successfully.");
    } catch (error) {
      toast.error("Failed to run TTL cleanup.");
    }
  };

  return (
    <div className="flex flex-col h-full p-4 space-y-4">
      <header className="py-4 border-b border-zinc-900">
        <h1 className="text-xl font-bold tracking-tight">Node Settings</h1>
        <p 
          className="text-xs font-mono text-zinc-500 mt-1 select-none active:text-zinc-400"
          onClick={handleSecretTap}
        >
          LOCAL_CONFIG: ACTIVE
        </p>
      </header>
      
      <div className="flex-1 space-y-6 mt-4 pb-8">
        <div className="space-y-2">
          <h2 className="text-xs font-mono text-zinc-500 uppercase tracking-widest">Identity</h2>
          <div className="bg-zinc-900/30 p-3 rounded border border-zinc-800 flex justify-between items-center">
            <span className="text-sm font-mono text-zinc-400">NODE_ID</span>
            <span className="text-sm font-mono text-zinc-100">usr_8f92a1b</span>
          </div>
        </div>

        <div className="space-y-2">
          <h2 className="text-xs font-mono text-zinc-500 uppercase tracking-widest">State Verification (Dev)</h2>
          <div className="bg-zinc-900/30 p-3 rounded border border-zinc-800 flex justify-between items-center">
            <span className="text-sm font-mono text-zinc-400">ZUSTAND_STORE</span>
            <button 
              onClick={() => setNavigating(!isNavigating)}
              className={`text-xs font-mono px-2 py-1 rounded border transition-colors ${
                isNavigating 
                  ? 'border-green-900/50 bg-green-950/20 text-green-500' 
                  : 'border-zinc-700 bg-zinc-800 text-zinc-300'
              }`}
            >
              NAVIGATING: {isNavigating ? 'TRUE' : 'FALSE'}
            </button>
          </div>
        </div>

        {devModeEnabled && (
          <div className="space-y-2 animate-in fade-in slide-in-from-bottom-2 duration-300">
            <h2 className="text-xs font-mono text-amber-500 uppercase tracking-widest flex items-center space-x-2">
              <span>Dev Tools Panel</span>
            </h2>
            <div className="bg-zinc-950 p-3 rounded-md border border-amber-900/50 flex flex-col space-y-3">
              <p className="text-xs font-mono text-zinc-500">DEXIE_JS_CONTROLS</p>
              
              <button 
                onClick={handleGenerateMessages}
                className="w-full py-2 bg-zinc-900 border border-zinc-800 text-zinc-300 text-xs font-mono rounded active:bg-zinc-800 transition-colors"
              >
                GENERATE 50 DUMMY MESSAGES
              </button>
              
              <button 
                onClick={handleTTL}
                className="w-full py-2 bg-zinc-900 border border-zinc-800 text-zinc-300 text-xs font-mono rounded active:bg-zinc-800 transition-colors"
              >
                TRIGGER TTL CLEANUP
              </button>

              <button 
                onClick={handleClearDatabase}
                className="w-full py-2 bg-red-950/20 border border-red-900/50 text-red-500 text-xs font-mono rounded active:bg-red-900/20 transition-colors"
              >
                CLEAR DATABASE
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
