import { useState, useRef } from "react";
import { useUIStore, useMessageStore, useNetworkStore } from "@/store";
import { toast } from "sonner";
import { db } from "@/db/db";
import { createMessage, deleteExpiredMessages } from "@/db/messages";
import { v4 as uuidv4 } from "uuid";
import type { Message, MessageType } from "@/types/message";
import { Smartphone, Trash2, Sparkles, Clock, ChevronRight } from "lucide-react";

import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";

export default function Settings() {
  const { isNavigating, setNavigating } = useUIStore();
  const { fetchMessages } = useMessageStore();
  const { myPeerId } = useNetworkStore();

  // Stealth Dev Mode State
  const [devModeEnabled, setDevModeEnabled] = useState(false);
  const tapCountRef = useRef(0);
  const tapTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const handleSecretTap = () => {
    if (devModeEnabled) return;

    if (tapTimeoutRef.current) {
      clearTimeout(tapTimeoutRef.current);
    }

    tapCountRef.current += 1;

    if (tapCountRef.current >= 5) {
      setDevModeEnabled(true);
      toast.success("Developer tools unlocked");
      tapCountRef.current = 0;
    } else {
      tapTimeoutRef.current = setTimeout(() => {
        tapCountRef.current = 0;
      }, 500);
    }
  };

  const handleGenerateMessages = async () => {
    try {
      const now = Date.now();
      const types: MessageType[] = ["alert", "news", "route", "resource"];
      for (let i = 0; i < 50; i++) {
        const type = types[Math.floor(Math.random() * types.length)];
        const msg: Message = {
          id: `msg_${uuidv4().substring(0, 8)}`,
          type,
          priority: type === "alert" ? "high" : "low",
          content: `Automated test message ${i + 1} generated by Dev Tools.`,
          createdAt: now - Math.floor(Math.random() * 10000000),
          updatedAt: now,
          expiresAt: now + 86400000,
          version: 1,
          hopCount: Math.floor(Math.random() * 5),
          maxHopCount: 10,
          trusted: true
        };
        await createMessage(msg);
      }
      await fetchMessages();
      toast.success("50 test messages generated");
    } catch (error) {
      console.error("handleGenerateMessages error:", error);
      toast.error("Failed to generate messages");
    }
  };

  const handleGenerateShortTTLMessage = async () => {
    try {
      const now = Date.now();
      const msg: Message = {
        id: `msg_${uuidv4().substring(0, 8)}`,
        type: "news",
        priority: "low",
        content: `Short TTL test message (Expires in 30 secs).`,
        createdAt: now,
        updatedAt: now,
        expiresAt: now + 30000,
        version: 1,
        hopCount: 0,
        maxHopCount: 10,
        trusted: true
      };
      await createMessage(msg);
      await fetchMessages();
      toast.success("30 sec TTL message generated");
    } catch (error) {
      console.error("handleGenerateShortTTLMessage error:", error);
      toast.error("Failed to generate TTL message");
    }
  };
  const handleTTL = async () => {
    try {
      await deleteExpiredMessages();
      await fetchMessages();
      toast.info("Expired messages cleaned up");
    } catch (error) {
      console.error("handleTTL error:", error);
      toast.error("Failed to clean up");
    }
  };

  const handleEmergencyWipe = async () => {
    try {
      // 1. Wipe DB
      await db.messages.clear();
      
      // 2. Unregister service workers
      if ("serviceWorker" in navigator) {
        const registrations = await navigator.serviceWorker.getRegistrations();
        for (const registration of registrations) {
          await registration.unregister();
        }
      }
      
      // 3. Reload window to clear memory and states
      window.location.reload();
    } catch (error) {
      console.error("handleEmergencyWipe error:", error);
      toast.error("Emergency wipe failed");
    }
  };

  return (
    <div className="flex flex-col h-full animate-fade-in-up">
      <header className="px-5 pt-6 pb-4">
        <h1 className="text-2xl font-bold tracking-tight">Settings</h1>
        <p
          className="text-xs text-zinc-500 mt-1 select-none active:text-zinc-400"
          onClick={handleSecretTap}
        >
          Manage your device and preferences
        </p>
      </header>

      <div className="flex-1 px-5 space-y-4 pb-8">

        {/* Device Info */}
        <div className="glass-card overflow-hidden">
          <div className="p-4 flex items-center gap-3">
            <div className="w-10 h-10 rounded-full bg-blue-500/10 flex items-center justify-center">
              <Smartphone className="w-5 h-5 text-blue-400" />
            </div>
            <div className="flex-1 min-w-0">
              <h3 className="text-sm font-medium text-zinc-300">Your Device</h3>
              <p className="text-xs text-zinc-500 mt-0.5">
                {myPeerId ? (
                  <>ID: <span className="text-zinc-400 font-semibold select-all">{myPeerId}</span></>
                ) : (
                  "Not connected to mesh"
                )}
              </p>
            </div>
            <ChevronRight className="w-4 h-4 text-zinc-700" />
          </div>
        </div>

        {/* Debug Mode (always visible but simple) */}
        <div className="glass-card overflow-hidden">
          <div className="p-4 flex items-center justify-between">
            <div>
              <h3 className="text-sm font-medium text-zinc-300">Debug Mode</h3>
              <p className="text-xs text-zinc-500 mt-0.5">Toggle navigation state for testing</p>
            </div>
            <button
              onClick={() => setNavigating(!isNavigating)}
              className={`px-3 py-1.5 rounded-full text-xs font-medium transition-all duration-200 ${isNavigating
                ? "bg-emerald-500/15 text-emerald-400"
                : "bg-white/5 text-zinc-500"
                }`}
            >
              {isNavigating ? "On" : "Off"}
            </button>
          </div>
        </div>

        {/* Dev Tools Panel */}
        {devModeEnabled && (
          <div className="space-y-2 animate-fade-in-up">
            <h2 className="text-xs font-medium text-amber-400/80 uppercase tracking-wider px-1 flex items-center gap-1.5">
              <Sparkles className="w-3.5 h-3.5" />
              Developer Tools
            </h2>
            <div className="glass-card overflow-hidden border-amber-500/10 divide-y divide-white/5">
              <button
                onClick={handleGenerateMessages}
                className="w-full p-4 text-left text-sm text-zinc-300 hover:bg-white/3 transition-colors flex items-center gap-3"
              >
                <Sparkles className="w-4 h-4 text-zinc-500" />
                Generate 50 test messages
              </button>

              <button
                onClick={handleTTL}
                className="w-full p-4 text-left text-sm text-zinc-300 hover:bg-white/3 transition-colors flex items-center gap-3"
              >
                <Clock className="w-4 h-4 text-zinc-500" />
                Clean up expired messages
              </button>
              <button
                onClick={handleGenerateShortTTLMessage}
                className="w-full p-4 text-left text-sm text-zinc-300 hover:bg-white/3 transition-colors flex items-center gap-3"
              >
                <Clock className="w-4 h-4 text-zinc-500" />
                Generate 30-sec TTL message
              </button>
            </div>
          </div>
        )}

        {/* Security / Danger Zone */}
        <div className="space-y-2 animate-fade-in-up mt-8">
          <h2 className="text-xs font-medium text-red-500/80 uppercase tracking-wider px-1 flex items-center gap-1.5">
            <Trash2 className="w-3.5 h-3.5" />
            Danger Zone
          </h2>
          <div className="glass-card overflow-hidden border-red-500/20">
            <AlertDialog>
              <AlertDialogTrigger asChild>
                <button className="w-full p-4 text-left text-sm text-red-400 font-medium hover:bg-red-500/10 transition-colors flex items-center gap-3">
                  <Trash2 className="w-4 h-4 text-red-500" />
                  Emergency Wipe
                </button>
              </AlertDialogTrigger>
              <AlertDialogContent className="bg-zinc-950 border border-red-500/30 text-zinc-100 max-w-sm rounded-xl">
                <AlertDialogHeader>
                  <AlertDialogTitle className="text-red-500">Emergency Wipe Data?</AlertDialogTitle>
                  <AlertDialogDescription className="text-zinc-400">
                    This action cannot be undone. This will instantly destroy all local databases, messages, and configurations, and unregister the offline service worker.
                  </AlertDialogDescription>
                </AlertDialogHeader>
                <AlertDialogFooter>
                  <AlertDialogCancel className="bg-white/5 border-white/10 hover:bg-white/10 text-zinc-100 rounded-lg">Cancel</AlertDialogCancel>
                  <AlertDialogAction onClick={handleEmergencyWipe} className="bg-red-500 hover:bg-red-600 text-white rounded-lg">
                    Nuke Everything
                  </AlertDialogAction>
                </AlertDialogFooter>
              </AlertDialogContent>
            </AlertDialog>
          </div>
        </div>

      </div>
    </div>
  );
}
